### ISSUE TITLE
Push a new release to rubygems.org to fix 'OpenSSL::Cipher::Cipher' error

### ISSUE THREAD

**Issue by mlpinit** [Shopify/dukpt#19]
Hello  @ryanbalsdon

I noticed this commit fixes the deprecation warning for `OpenSSL::Cipher::Cipher` https://github.com/Shopify/dukpt/blob/master/lib/dukpt/encryption.rb#L142

Is there anything I can help with to push a new release to rubygems.org ?

**Comment by ryanbalsdon** [comment]
Hi Marius,

I'll forward this on to a few people still at Shopify but I don't have access to the key to push this up anymore.

Sorry!
Ryan

**Comment by devesh-shetty** [comment]
Hi @mlpinit 
I pushed v0.0.5 https://rubygems.org/gems/dukpt
Apologies for the delay
